spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kamilszymanski707/git-config.git
          search-paths:
            - ${git-root-search-path}
            - '${git-root-search-path}/{application}'
          default-label: main

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://127.0.0.1:8761/eureka/}
